In [1]:
import pandas as pd
import numpy as np
#Imports data
rb_raw=pd.read_csv('RB_Performance.csv')

In [2]:
#Data Types
rb_raw.dtypes

Player                 object
Year                  float64
Tm                     object
Age                   float64
GP                    float64
% of Snaps            float64
# of Snaps            float64
Total Touches         float64
Rush Att              float64
Rush Yds              float64
Yards/Att             float64
Target                float64
Reception             float64
Receiving Yards       float64
Yards/Rec             float64
Rush TD               float64
Rec TD                float64
Total TD              float64
Touch/TD               object
Fumbles               float64
20+ Yard              float64
40+ Yard              float64
Red Zone Rush Att     float64
Red Zone Yards        float64
Red Zone Y/A          float64
Red Zone Rush TD      float64
Red Zone Targets      float64
Red Zone Rec          float64
Red Zone Catch %      float64
Red Rec Zone TD       float64
Target Share %        float64
Fantasy Point         float64
FF PPG                float64
P/Snap                float64
100+ Yrd/games        float64
Games w/TD            float64
18+ Touch             float64
Top 12                float64
Perfromance Metric     object
Points/Touch          float64
Point/Touch-TD         object
Unnamed: 41           float64
Unnamed: 42           float64
dtype: object

In [3]:
rb_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 561 entries, 0 to 560
Data columns (total 43 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Player              560 non-null    object
 1   Year                560 non-null    float64
 2   Tm                  560 non-null    object
 3   Age                 560 non-null    float64
 4   GP                  560 non-null    float64
 5   % of Snaps          560 non-null    float64
 6   # of Snaps          560 non-null    float64
 7   Total Touches       560 non-null    float64
 8   Rush Att            560 non-null    float64
 9   Rush Yds            560 non-null    float64
 10  Yards/Att           560 non-null    float64
 11  Target              560 non-null    float64
 12  Reception           560 non-null    float64
 13  Receiving Yards     560 non-null    float64
 14  Yards/Rec           560 non-null    float64
 15  Rush TD             558 non-null    float64
 16  Rec TD              558 non-null    float64
 17  Total TD            560 non-null    float64
 18  Touch/TD            560 non-null    object
 19  Fumbles             540 non-null    float64
 20  20+ Yard            441 non-null    float64
 21  40+ Yard            441 non-null    float64
 22  Red Zone Rush Att   442 non-null    float64
 23  Red Zone Yards      560 non-null    float64
 24  Red Zone Y/A        442 non-null    float64
 25  Red Zone Rush TD    442 non-null    float64
 26  Red Zone Targets    442 non-null    float64
 27  Red Zone Rec        442 non-null    float64
 28  Red Zone Catch %    442 non-null    float64
 29  Red Rec Zone TD     442 non-null    float64
 30  Target Share %      559 non-null    float64
 31  Fantasy Point       560 non-null    float64
 32  FF PPG              560 non-null    float64
 33  P/Snap              559 non-null    float64
 34  100+ Yrd/games      560 non-null    float64
 35  Games w/TD          559 non-null    float64
 36  18+ Touch           560 non-null    float64
 37  Top 12              560 non-null    float64
 38  Perfromance Metric  560 non-null    object
 39  Points/Touch        559 non-null    float64
 40  Point/Touch-TD      560 non-null    object
 41  Unnamed: 41         0 non-null      float64
 42  Unnamed: 42         0 non-null      float64
dtypes: float64(38), object(5)
memory usage: 188.6+ KB

In [4]:
#Fills NA's with 0
rb_raw=rb_raw.fillna(0)

rb_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 561 entries, 0 to 560
Data columns (total 43 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Player              561 non-null    object
 1   Year                561 non-null    float64
 2   Tm                  561 non-null    object
 3   Age                 561 non-null    float64
 4   GP                  561 non-null    float64
 5   % of Snaps          561 non-null    float64
 6   # of Snaps          561 non-null    float64
 7   Total Touches       561 non-null    float64
 8   Rush Att            561 non-null    float64
 9   Rush Yds            561 non-null    float64
 10  Yards/Att           561 non-null    float64
 11  Target              561 non-null    float64
 12  Reception           561 non-null    float64
 13  Receiving Yards     561 non-null    float64
 14  Yards/Rec           561 non-null    float64
 15  Rush TD             561 non-null    float64
 16  Rec TD              561 non-null    float64
 17  Total TD            561 non-null    float64
 18  Touch/TD            561 non-null    object
 19  Fumbles             561 non-null    float64
 20  20+ Yard            561 non-null    float64
 21  40+ Yard            561 non-null    float64
 22  Red Zone Rush Att   561 non-null    float64
 23  Red Zone Yards      561 non-null    float64
 24  Red Zone Y/A        561 non-null    float64
 25  Red Zone Rush TD    561 non-null    float64
 26  Red Zone Targets    561 non-null    float64
 27  Red Zone Rec        561 non-null    float64
 28  Red Zone Catch %    561 non-null    float64
 29  Red Rec Zone TD     561 non-null    float64
 30  Target Share %      561 non-null    float64
 31  Fantasy Point       561 non-null    float64
 32  FF PPG              561 non-null    float64
 33  P/Snap              561 non-null    float64
 34  100+ Yrd/games      561 non-null    float64
 35  Games w/TD          561 non-null    float64
 36  18+ Touch           561 non-null    float64
 37  Top 12              561 non-null    float64
 38  Perfromance Metric  561 non-null    object
 39  Points/Touch        561 non-null    float64
 40  Point/Touch-TD      561 non-null    object
 41  Unnamed: 41         561 non-null    float64
 42  Unnamed: 42         561 non-null    float64
dtypes: float64(38), object(5)
memory usage: 188.6+ KB

In [5]:
#COnverts Performance Metric to a float
rb_raw['Perfromance Metric']=pd.to_numeric(rb_raw['Perfromance Metric'],errors='coerce')

rb_raw.dtypes

Player                 object
Year                  float64
Tm                     object
Age                   float64
GP                    float64
% of Snaps            float64
# of Snaps            float64
Total Touches         float64
Rush Att              float64
Rush Yds              float64
Yards/Att             float64
Target                float64
Reception             float64
Receiving Yards       float64
Yards/Rec             float64
Rush TD               float64
Rec TD                float64
Total TD              float64
Touch/TD               object
Fumbles               float64
20+ Yard              float64
40+ Yard              float64
Red Zone Rush Att     float64
Red Zone Yards        float64
Red Zone Y/A          float64
Red Zone Rush TD      float64
Red Zone Targets      float64
Red Zone Rec          float64
Red Zone Catch %      float64
Red Rec Zone TD       float64
Target Share %        float64
Fantasy Point         float64
FF PPG                float64
P/Snap                float64
100+ Yrd/games        float64
Games w/TD            float64
18+ Touch             float64
Top 12                float64
Perfromance Metric    float64
Points/Touch          float64
Point/Touch-TD         object
Unnamed: 41           float64
Unnamed: 42           float64
dtype: object

In [6]:
#Grabs features that I want to run machine learning on
data_rb=rb_raw.loc[:,['Player','GP','% of Snaps','# of Snaps','Total Touches','Total TD','100+ Yrd/games','Games w/TD','Top 12','Perfromance Metric']]

data_rb=data_rb.dropna()

data_rb.head()
#Target Variable
target=data_rb.iloc[:,-1]
#Feature Variable
features=data_rb.iloc[:,[0,1,2,3,4,5,6,7,8]]

col_names=data_rb.columns

features

,Player,GP,% of Snaps,# of Snaps,Total Touches,Total TD,100+ Yrd/games,Games w/TD,Top 12
0,Aaron Jones,12.0,0.35,376.0,159.0,9.0,3.0,7.0,6.0
1,Adrian Peterson,16.0,0.47,481.0,270.0,7.0,5.0,5.0,5.0
2,Alex Armah,16.0,0.06,65.0,10.0,2.0,0.0,2.0,0.0
3,Alex Collins,10.0,0.26,311.0,129.0,8.0,0.0,7.0,2.0
4,Alfred Blue,16.0,0.42,461.0,169.0,2.0,1.0,2.0,1.0
...,...,...,...,...,...,...,...,...,...
556,Adrian Peterson,15.0,0.42,407.0,228.0,5.0,3.0,5.0,2.0
557,Chris Thompson,11.0,0.33,317.0,79.0,0.0,1.0,0.0,0.0
558,Derrius Guice,5.0,0.10,98.0,49.0,3.0,1.0,2.0,1.0
559,Wendell Smallwood,12.0,0.15,143.0,31.0,0.0,0.0,0.0,0.0
560,0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0

In [32]:
#Scales data
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scale_data=scaler.fit(data_rb)
scale_data=scaler.transform(data_rb)


scale_data=pd.DataFrame(scale_data)
scale_data.columns=col_names
#Correlation Matrix 
corr_matrix=scale_data.corr()
#Correlation Matrix for Performance Metric
corr_matrix['Perfromance Metric'].sort_values(ascending=False)

Perfromance Metric    1.000000
Top 12                0.945938
100+ Yrd/games        0.924720
Total Touches         0.890534
Total TD              0.876833
% of Snaps            0.864551
# of Snaps            0.863822
Games w/TD            0.845579
GP                    0.422738
Name: Perfromance Metric, dtype: float64

In [7]:
#Splits data into train and testing samples
from sklearn.model_selection import train_test_split

X_train,X_test,Y_train,Y_test=train_test_split(features,target, test_size=.2, random_state=42)

player_test=X_test.loc[:,'Player']
player_train=X_train.loc[:,'Player']

X_train=X_train.drop(['Player'],axis=1)
X_test=X_test.drop(['Player'],axis=1)

In [8]:
#Linear Regression Model
from sklearn.linear_model import LinearRegression
lm_model=LinearRegression()
lm_model.fit(X_train,Y_train)
lm_predict=lm_model.predict(X_test)

print('R^2 score :',lm_model.score(X_train,Y_train))

R^2 score : 0.9444047057421953

In [9]:
#Cross Validation Score
from sklearn.model_selection import cross_val_score
cross_val_score(lm_model,X_train,Y_train,cv=10).mean()

0.9335274759219621

In [10]:
#Finds the mean squared error. Lower the number the less errors, hence more accurate
from sklearn.metrics import mean_squared_error

lm_mse=mean_squared_error(Y_test,lm_predict)

print('Mean Squared Error for Linear Regression :',lm_mse)

Mean Squared Error for Linear Regression : 10.158258415220132

In [11]:
#Create a dataframe of actual and predicted results


actual_predict=pd.DataFrame(list(zip(Y_test,lm_predict)),columns=['Actual Performance Metric','Predicted Performance Metric'])

actual_predict

     Actual Performance Metric  Predicted Performance Metric
0                         0.34                     -1.346140
1                         0.13                     -0.264524
2                         5.53                      4.887390
3                         6.51                      2.822022
4                         6.61                      8.536826
..                         ...                           ...
106                      12.89                     14.132155
107                       6.01                      3.091387
108                      26.87                     28.337883
109                      14.10                     18.137477
110                      31.49                     32.998593

[111 rows x 2 columns]

In [12]:
#Random Forest Regressor
from sklearn.ensemble import RandomForestRegressor

rf_model=RandomForestRegressor(n_estimators=100,oob_score=True,max_depth=3,random_state=42)

rf_model.fit(X_train,Y_train)

rf_predict=rf_model.predict(X_test)

In [13]:
#Out of box score, similar to R^2 for linear regression
rf_model.oob_score_

0.9403732092031335

In [14]:
#Cross validation score for Random Forest Regressor
cross_val_score(rf_model,X_train,Y_train,cv=10).mean()

0.9370731430108684

In [15]:
#Mean Squared Error
rf_mse=mean_squared_error(Y_test,rf_predict)

print('Root Mean Squared Error Random Forest:',np.sqrt(rf_mse))

Root Mean Squared Error Random Forest: 3.1769328954726492

In [16]:
#Dataframe of actual vs predicted results of Performance Metric
rf_actual_predict=pd.DataFrame(list(zip(Y_test,rf_predict)),columns=['Actual Performance Metric','Predicted Performance Metric'])

rf_actual_predict

     Actual Performance Metric  Predicted Performance Metric
0                         0.34                      1.324504
1                         0.13                      1.324504
2                         5.53                      2.662739
3                         6.51                      5.598049
4                         6.61                      2.848433
..                         ...                           ...
106                      12.89                     12.259961
107                       6.01                      5.598049
108                      26.87                     32.533039
109                      14.10                     13.662279
110                      31.49                     37.461347

[111 rows x 2 columns]

I performed two machine learning techniques to determine how predictable Performance Metric is based of of several features. I used a multi-linear regression and a Random Forest Regression to compare which algorithm performed best. While both model performed similary, the Random Forest Regressor had a higher cross validation score and a lower mean squared error. Therefore, out of the two models, the Random Forest Regressor would be the perferred choice in predicted Performance Metric Accuracy.